# custom-monitoring.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: custom_standard_deviation

trigger:
  type: recurrence
  frequency: day # can be minute, hour, day, week, month
  interval: 7 # #every day

create_monitor:
  compute:
    instance_type: "standard_e8s_v3"
    runtime_version: "3.3"

  monitoring_signals:
    customSignal:
      type: custom
      component_id: azureml:my_custom_signal_taxi:1.0.0
      input_data:
        production_data:
          input_data:
            type: uri_folder
            path: azureml:taxi-monit-oe-demo-cv-online-dp-model_outputs:1 #azureml://subscriptions/4c0c62e4-fef0-4e04-8d12-d43960250eaa/resourcegroups/rg-ncai-testing/workspaces/ncai-test/datastores/workspaceblobstore/paths/modelDataCollector/taxi-monit-oe-demo/cv-online-dp/model_outputs/
          data_context: test
          data_window:
            trailing_window_size: P30D
            trailing_window_offset: P7D
          pre_processing_component: azureml:custom_preprocessor_taxi:1.0.0
      metric_thresholds:
        - metric_name: std_deviation
          threshold: 2
  alert_notification:
    emails:
      - raquelmo@microsoft.com
    # customSignal:
    #   type: custom
    #   component_id: azureml:my_custom_signal_taxi:1.0.0
    #   input_data:
    #     production_data:
    #       input_data:
    #         type: uri_folder
    #         path: azureml:taxi-monit-oe-demo-cv-online-dp-model_outputs:1
    #       data_window_start: "2023-11-11T04:31:57.012Z"
    #       data_window_end: "2023-12-12T04:31:57.012Z"          
    #       pre_processing_component: azureml:custom_preprocessor_taxi:1.0.0
        # test_data_2:
        #   input_data:
        #     type: mltable
        #     path: azureml:azureml_af32e13a-4d7f-491f-ad6f-0320de263383_output_data_preprocessed_input_data:1
        #   data_context: test
        # data_window:
        #   trailing_window_size: P30D
        #   trailing_window_offset: P7D          
        #   pre_processing_component: azureml:custom_preprocessor:1.0.0

