#User Config
postfix: "1"
route_table_name: "ROUTE-2-FIREWALL-AMS-04"
location: "westeurope"
environment: "dev"
# enable_aml_computecluster: true
# enable_aml_secure_workspace: true
# enable_monitoring: true
# module_version: "feature/pre-release"

terraform_version: 0.14.7
terraform_workingdir: infrastructure/terraform
resource_group: "rg-daimler"
storage_account: "testboth123"
storage_container: "testfile123"