# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
# - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
#     # 'main' branch: PRD environment
#     - template: ../../config-infra-prod.yml
# - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    # 'develop' or feature branches: DEV environment
    - template: ../../terragrunt/config-infra-dev.yml

trigger:
- none

pool:
  vmImage: ubuntu-latest

# resources:
#   repositories:
#     - repository: mlops-templates
#       name: Azure/mlops-templates
#       endpoint: github-connection
#       type: github
#       ref: main #branch name

stages :
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
    - job: CreateStorageForTerraform
      displayName: Create Storage for Terraform
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/infra/create-resource-group.yml@mlops-templates
      - template: templates/infra/create-storage-account.yml@mlops-templates
      - template: templa>tes/infra/create-storage-container.yml@mlops-templates

  - stage: DeployDataFactory
    displayName: Deploy Data Factory
    jobs:
    - job:  DeployDataFactory
      displayName: Deploy Terraform
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/infra/install-terraform.yml@mlops-templates
      - template: templates/infra/run-terraform-init.yml@mlops-templates
      - template: templates/infra/run-terraform-validate.yml@mlops-templates
      - template: templates/infra/run-terraform-plan.yml@mlops-templates
      - template: templates/infra/run-terraform-apply.yml@mlops-templates
    - job: waitForValidation
      displayName: Wait for external validation  
      timeoutInMinutes: 4320 # job times out in 3 days
      steps:   
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            raquelmo@microsoft.com
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'resume'
